--Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue
from consumer
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount 
from consumer 
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from consumer);

-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from consumer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type,  round(avg(purchase_amount),2)
from consumer
where shipping_type in ('Standard','Express')
group by shipping_type;

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status,
       count(customer_id) as total_customers,
       round(avg(purchase_amount),2) as avg_spend,
       round(sum(purchase_amount),2) as total_revenue
from consumer
group by subscription_status
order by total_revenue,avg_spend desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
       round(100.0 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(*),2) as discount_rate
from consumer
group by item_purchased
order by discount_rate desc
limit 5;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
select customer_id, previous_purchases,
case 
    when previous_purchases = 1 then 'New'
    when previous_purchases BETWEEN 2 and 10 then 'Returning'
    else 'Loyal'
    end as customer_segment
from consumer)

select customer_segment,count(*) as "Number of Customers" 
from customer_type 
group by customer_segment
order by count(*) desc;

--Q8. What are the top 3 most purchased products within each category? 
with item_counts as (
    select category,
           item_purchased,
           count(customer_id) as total_orders,
           row_number() over (partition by category order by count(customer_id) desc) as item_rank
    from consumer
    group by category, item_purchased
)
select item_rank,category, item_purchased, total_orders
from item_counts
where item_rank <=3;
 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
       count(customer_id) as repeat_buyers
from consumer
where previous_purchases > 5
group by subscription_status;

--Q10. What is the revenue contribution of each age group? 
select age_group, sum(purchase_amount) as total_revenue
from consumer
group by age_group
order by total_revenue desc;

--Q11. Does the investment in faster shipping correlate with a measurable increase in loyalty
--(i.e., faster repeat purchases) for subscribed customers?
select shipping_type, round(avg(purchase_frequency_days)) as avg_days_to_next_purchase
from consumer
where subscription_status = 'Yes'
group by shipping_type
order by avg_days_to_next_purchase asc;

--Q12. Pinpoint the most successful (high-AOV, high-satisfaction) product categories in specific
--geographic markets for targeted scaling.
select
    location,
    category,
    round(avg(purchase_amount), 2) as average_order_value,
    round(avg(review_rating::numeric), 2) as average_rating
from
    consumer
group by
    location, category
having
    round(avg(purchase_amount), 2) > (select avg(purchase_amount) from consumer) -- AOV above overall average
    and round(avg(review_rating::numeric), 2) >= 4.0 -- High satisfaction threshold
order by
    location, average_order_value DESC;

--Q13. Define the profile of the most loyal customers using previous_purchases as a proxy for lifetime value.
with RankedCustomers as (
    -- Rank customers based on their total previous purchases to find the top 15%
    select
        customer_id,
        gender,
        age,
        payment_method,
        ntile(100) over (order by previous_purchases DESC) as percentile_rank
    from
        consumer
)
select
    gender,
    payment_method,
    round(avg(age), 0) as median_age,
    count(customer_id) as total_top_customers
from
    RankedCustomers
where
    percentile_rank <= 15 -- selects the top 15 percent
group by
    gender, payment_method
order by
    total_top_customers DESC;

--Q14. Determine if specific modern payment methods (like PayPal/Venmo) are correlated
--with a higher long-term customer count (previous_purchases).
select
    payment_method,
    round(avg(previous_purchases), 0) as average_lifetime_purchases,
    count(customer_id) as total_customers_using_method
from
    consumer
group by
    payment_method
order by
    average_lifetime_purchases DESC;

--Q15. Measure the effectiveness of extending the sales season for typically seasonal items (Outerwear),
--indicating success of product lifecycle strategies.
select
    'Outerwear' as category,
    round(
        sum(case when season <> 'Winter' then purchase_amount else 0 end) * 100.0 / sum(purchase_amount), 2
    ) as percent_sales_off_season
from
    consumer
where
    category = 'Outerwear';

--Q16. Identify specific market segments (age_group and item_purchased) that are experiencing the lowest
--satisfaction, pointing directly to quality or targeting failures.
select
    age_group,
    item_purchased,
    round(avg(review_rating::numeric), 2) as average_rating,
    count(customer_id) as total_purchases
from
    consumer
group by
    age_group, item_purchased
having
    count(customer_id) >= 0 -- Ensure minimum volume for a reliable average
order by
    average_rating asc
limit 5;